# Generated by Django 4.2.30 on 2026-07-05 13:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('category', models.CharField(choices=[('library', 'Library'), ('labs', 'Labs'), ('wifi', 'Wi-Fi'), ('canteen', 'Canteen'), ('cleanliness', 'Cleanliness'), ('hostel', 'Hostel'), ('placement', 'Placement Cell'), ('sports', 'Sports'), ('infrastructure', 'Infrastructure'), ('administration', 'Administration'), ('events', 'Events'), ('other', 'Other')], max_length=30)),
                ('text', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('in_progress', 'In Progress'), ('implemented', 'Implemented'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('upvote_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SuggestionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('responded_by_role', models.CharField(default='Administration', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('suggestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='suggestions.collegesuggestion')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SuggestionUpvote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_token', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('suggestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upvotes', to='suggestions.collegesuggestion')),
            ],
            options={
                'unique_together': {('suggestion', 'device_token')},
            },
        ),
    ]
